name: Azure login test
run-name: Azure login test

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - dev  

jobs:
  azure_login:
    name: Azure login
    runs-on: windows-latest
    environment: TEST
    steps:
      - name: Azure Login
        uses: Azure/login@v1.4.6
        with:
          creds: '{"clientId": "ec755ded-9fa9-4eeb-8e19-80e886940fd9","clientSecret": "3Xk8Q~5lWw5jUoPVx3m.AHi-_JG9~fWuBoO1ebhW","subscriptionId": "0417ba2f-23e4-4c31-93be-75e376017b03","tenantId": "83f1e4bf-6250-46ba-9d55-4fc1c00efb85"}'
          enable-AzPSSession: true
