name: Deploy Ingestion ADF to PROD2
run-name: Deploy Ingestion ADF to PROD2

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build_ARM_templates:
    name: Build ARM templates
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.5

      - name: Export ARM templates
        id: export
        uses: ./.github/actions/data-factory-export-action
        with:
          path: Ingestion
          id: /subscriptions/0417ba2f-23e4-4c31-93be-75e376017b03/resourceGroups/Chinnamamaya-RG/providers/Microsoft.DataFactory/factories/lk-adf-001

      - name: check
        run: |
          echo "${{steps.export.outputs.arm-template-directory }}"
          ls ${{steps.export.outputs.arm-template-directory }}
      
      - name: Upload ARM templates artifact
        uses: actions/upload-artifact@v4.3.3
        with:
          name: armtemplates
          path: ${{steps.export.outputs.arm-template-directory }}
          if-no-files-found: error
