name: Deploy Ingestion ADF
run-name: Deploy Ingestion ADF

on:
  workflow_dispatch: 
  # pull_request:
  #   types: [closed]
  #   branches: [test]
    
jobs:
  build_ARM_templates:
    name: Build ARM templates
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.2.0

  # Installs Node and the npm packages saved in your package.json file in the build
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.4.1
        with:
          node-version: 18.x
          
      - name: install ADF Utilities package
        run: npm install
        working-directory: ${{github.workspace}}/Ingestion/build  # (1) provide the folder location of the package.json file
          
  # Validates all of the Data Factory resources in the repository. You'll get the same validation errors as when "Validate All" is selected.
      - name: Validate
        run: npm run build validate ${{github.workspace}}/Ingestion/ /subscriptions/0417ba2f-23e4-4c31-93be-75e376017b03/resourceGroups/Chinnamamaya-RG/providers/Microsoft.DataFactory/factories/lk-adf-001
        working-directory: ${{github.workspace}}/Ingestion/build
          
      - name: Validate and Generate ARM template
        run: npm run build export ${{github.workspace}}/Ingestion/ /subscriptions/0417ba2f-23e4-4c31-93be-75e376017b03/resourceGroups/Chinnamamaya-RG/providers/Microsoft.DataFactory/factories/lk-adf-001
        working-directory: ${{github.workspace}}/Ingestion/build

      - name: Upload ARM templates artifact
        uses: actions/upload-artifact@v3.1.1
        with:
          name: armtemplates
          path: ${{steps.export.outputs.arm-template-directory }}
          if-no-files-found: error
