name: Deploy Ingestion ADF to PROD2
run-name: Deploy Ingestion ADF to PROD2

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build_ARM_templates:
    name: Build ARM templates
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.5

      - name: Export ARM templates
        id: export
        uses: ./.github/actions/data-factory-export-action
        with:
          path: Ingestion
          id: /subscriptions/0417ba2f-23e4-4c31-93be-75e376017b03/resourceGroups/Chinnamamaya-RG/providers/Microsoft.DataFactory/factories/lk-adf-001

      - name: check
        run: |
          echo "${{steps.export.outputs.arm-template-directory }}"
          ls ${{steps.export.outputs.arm-template-directory }}
      
      - name: Upload ARM templates artifact
        uses: actions/upload-artifact@v4.3.3
        with:
          name: armtemplates
          path: ${{steps.export.outputs.arm-template-directory }}
          if-no-files-found: error

  deploy_to_uat_ingestion_adf:
    # if: ${{ github.ref == 'refs/heads/uat' || github.ref_name == 'uat' }}
    needs: [build_ARM_templates]
    name: Deploy to TEST ADF
    runs-on: ubuntu-latest
    environment: TEST
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.2.0

      - name: retrive SPN Certificate and private key - PEM file - from github secrets and save file
        env: 
          spn_certificate: ${{secrets.AZURE_SPN_CERTIFICATE_ACC}}
        run: |
          touch ./temp_cert_and_private_key_acc.pem
          echo "$spn_certificate" >> ./temp_cert_and_private_key_acc.pem
          
      - name: Azure login
        shell: pwsh
        run : |
          Install-Module Az -Force
          Connect-AzAccount -ServicePrincipal -ApplicationId ${{secrets.AZURE_SPN_APP_ID_ACC}} -TenantId ${{secrets.AZURE_SPN_TENET}} -CertificatePath './temp_cert_and_private_key_acc.pem'  
          az login --service-principal -u ${{secrets.AZURE_SPN_APP_ID_ACC}} -p temp_cert_and_private_key_acc.pem --tenant ${{secrets.AZURE_SPN_TENET}}
          
      - name: Download ARM templates artifact
        uses: actions/download-artifact@v3.0.1
        with:
          name: armtemplates
          path: armtemplates

      - name: Deploy to TEST
        uses: Azure/data-factory-deploy-action@v1.2.0
        with:
          resourceGroupName: Chinnamamaya-RG
          dataFactoryName: lk-adf-002
          armTemplateFile: ./armtemplates/ARMTemplateForFactory.json
################### End of workflow file ###################
