name: Test
run-name: Test

on:
  workflow_dispatch: 
  # pull_request:
  #   types: [closed]
  #   branches: [test]
    
jobs:
  build_ARM_templates:
    name: Build ARM templates
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.2.0

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: check-node-version
        # You may pin to the exact commit or the version.
        # uses: matzkoh/check-node-version@6c1f514d361250610d2a595d5c0ef96f54c8e2e9
        uses: matzkoh/check-node-version@v1.0.0          
