name: CICD with client secret
run-name: CICD with client secret

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - main

jobs:
  Build_ARM_templates:
    name: Build ARM templates
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.5

      - name: Export ARM templates
        id: export
        uses: ./.github/actions/data-factory-export-action
        with:
          path: Ingestion
          id: /subscriptions/0417ba2f-23e4-4c31-93be-75e376017b03/resourceGroups/Chinnamamaya-RG/providers/Microsoft.DataFactory/factories/lk-adf-001
      
      - name: Upload ARM templates artifact
        uses: actions/upload-artifact@v4.3.3
        with:
          name: armtemplates
          path: ${{steps.export.outputs.arm-template-directory }}
          if-no-files-found: error

  Deploy_to_TEST_ADF:
    needs: [Build_ARM_templates]
    name: Deploy to TEST ADF
    runs-on: ubuntu-latest
    environment: TEST
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.5

      - name: Azure login
        shell: pwsh
        run: |
          Install-Module Az -Force
          az login --service-principal -u 'ec755ded-9fa9-4eeb-8e19-80e886940fd9' --tenant '83f1e4bf-6250-46ba-9d55-4fc1c00efb85' -p '3Xk8Q~5lWw5jUoPVx3m.AHi-_JG9~fWuBoO1ebhW'
               
                      
      - name: Download ARM templates artifact
        uses: actions/download-artifact@v4.1.7
        with:
          name: armtemplates
          path: armtemplates

      - name: Deploy to TEST
        uses: Azure/data-factory-deploy-action@v1.2.0
        with:
          resourceGroupName: Chinnamamaya-RG
          dataFactoryName: lk-adf-002
          armTemplateFile: ./armtemplates/ARMTemplateForFactory.json
          armTemplateParametersFile: ./armtemplates/ARMTemplateParametersForFactory.json
################### End of workflow file ###################
